apiVersion: apps/v1
kind: Deployment
metadata:
  name: catch-the-banana
  namespace: demos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: catch-the-banana
  template:
    metadata:
      labels:
        app: catch-the-banana
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
        usage: tempworkloads
      tolerations:
      - key: "usage"
        operator: "Equal"
        value: "tempworkloads"
        effect: "NoSchedule"
      containers:
      - image: jannemattila/catch-the-banana:1.0.57
        name: catch-the-banana
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
